package engine

// Static atoms for Reflect, the ES2023 array and string methods and Annex B. They live apart from atoms.go so parallel
// additions to that table merge mechanically; staticAtom deduplicates names.
var (
	AtomReflect               = staticAtom("Reflect")
	AtomConstruct             = staticAtom("construct")
	AtomDeleteProperty        = staticAtom("deleteProperty")
	AtomHas                   = staticAtom("has")
	AtomOwnKeys               = staticAtom("ownKeys")
	AtomCopyWithin            = staticAtom("copyWithin")
	AtomToReversed            = staticAtom("toReversed")
	AtomToSorted              = staticAtom("toSorted")
	AtomToSpliced             = staticAtom("toSpliced")
	AtomWith                  = staticAtom("with")
	AtomIsWellFormed          = staticAtom("isWellFormed")
	AtomToWellFormed          = staticAtom("toWellFormed")
	AtomToLocaleLowerCase     = staticAtom("toLocaleLowerCase")
	AtomToLocaleUpperCase     = staticAtom("toLocaleUpperCase")
	AtomTrimLeft              = staticAtom("trimLeft")
	AtomTrimRight             = staticAtom("trimRight")
	AtomAnchor                = staticAtom("anchor")
	AtomBig                   = staticAtom("big")
	AtomBlink                 = staticAtom("blink")
	AtomBold                  = staticAtom("bold")
	AtomFixed                 = staticAtom("fixed")
	AtomFontcolor             = staticAtom("fontcolor")
	AtomFontsize              = staticAtom("fontsize")
	AtomItalics               = staticAtom("italics")
	AtomLink                  = staticAtom("link")
	AtomSmall                 = staticAtom("small")
	AtomStrike                = staticAtom("strike")
	AtomSub                   = staticAtom("sub")
	AtomSup                   = staticAtom("sup")
	AtomEscape                = staticAtom("escape")
	AtomUnescape              = staticAtom("unescape")
	AtomAtob                  = staticAtom("atob")
	AtomBtoa                  = staticAtom("btoa")
	AtomCode                  = staticAtom("code")
	AtomInvalidCharacterError = staticAtom("InvalidCharacterError")
	AtomSumPrecise            = staticAtom("sumPrecise")
	AtomDefineGetter          = staticAtom("__defineGetter__")
	AtomDefineSetter          = staticAtom("__defineSetter__")
	AtomLookupGetter          = staticAtom("__lookupGetter__")
	AtomLookupSetter          = staticAtom("__lookupSetter__")
	AtomIsError               = staticAtom("isError")
)
