package test262

import (
	"cmp"
	"fmt"
	"regexp"
	"slices"
	"sort"
	"strings"
	"time"
)

// Report is one run of the suite, rendered as RESULTS.md.
type Report struct {
	Revision string // the REVISION file
	Results  []Result
	Wall     time.Duration
	Workers  int
}

type counts struct{ pass, fail, skip int }

func (c *counts) add(s Status) {
	switch s {
	case Pass:
		c.pass++
	case Fail:
		c.fail++
	default:
		c.skip++
	}
}

func (c counts) total() int { return c.pass + c.fail + c.skip }

// rate is the pass rate of the tests that ran.
func (c counts) rate() string {
	if c.pass+c.fail == 0 {
		return "-"
	}
	return fmt.Sprintf("%.1f%%", 100*float64(c.pass)/float64(c.pass+c.fail))
}

// Group is the row of a test in the per-directory table: harness, or the
// first directory under language/, built-ins/ or annexB/.
func Group(path string) string {
	parts := strings.SplitN(path, "/", 3)
	if parts[0] == "harness" || len(parts) < 3 {
		return parts[0]
	}
	return parts[0] + "/" + parts[1]
}

var (
	guillemetsRE = regexp.MustCompile(`«[^»]*»`)
	digitsRE     = regexp.MustCompile(`\b[0-9]+\b`) // not inside names: Test262Error, Int16Array
)

// Category groups a failure message: assertion messages keep only the
// harness's "Expected ..." part (the test's own message varies per test),
// and values and numbers are elided.
func Category(msg string) string {
	if strings.HasPrefix(msg, "Test262Error: ") {
		if i := strings.LastIndex(msg, "Expected "); i > 0 {
			msg = "Test262Error: " + msg[i:]
		}
	}
	msg = guillemetsRE.ReplaceAllString(msg, "«…»")
	msg = digitsRE.ReplaceAllString(msg, "N")
	if r := []rune(msg); len(r) > 110 {
		msg = string(r[:110]) + "…"
	}
	return msg
}

// Markdown renders the report.
func (rep *Report) Markdown() string {
	var b strings.Builder
	var all, scope, annexB counts
	groups := map[string]*counts{}
	skips := map[string]int{}
	type featureRow struct {
		counts
		only int // skipped tests for which this is the only unimplemented feature
	}
	features := map[string]*featureRow{}
	categories := map[string][]string{}
	var panics, timeouts []Result
	for _, res := range rep.Results {
		all.add(res.Status)
		g := Group(res.Path)
		switch {
		case strings.HasPrefix(g, "annexB/"):
			annexB.add(res.Status)
		case g != "harness":
			scope.add(res.Status)
		}
		if groups[g] == nil {
			groups[g] = &counts{}
		}
		groups[g].add(res.Status)
		for _, f := range res.Features {
			if features[f] == nil {
				features[f] = &featureRow{}
			}
			features[f].add(res.Status)
		}
		switch {
		case res.Status == Skip:
			kind, _, _ := strings.Cut(res.Message, ": ")
			if kind == "feature" {
				kind = "unimplemented feature"
			}
			skips[kind]++
			if len(res.Blockers) == 1 {
				features[res.Blockers[0]].only++
			}
		case res.Status == Fail:
			c := Category(res.Message)
			if res.Panic {
				panics = append(panics, res)
				c = "panic"
			}
			if strings.HasPrefix(res.Message, "timeout") {
				timeouts = append(timeouts, res)
			}
			categories[c] = append(categories[c], res.Path)
		}
	}

	rev, _, _ := strings.Cut(strings.TrimSpace(rep.Revision), "\n")
	fmt.Fprintf(&b, `# test262 results

Generated by `+"`go test -run TestTest262 ./test262/ -update`"+` in the bench module; do not
edit by hand. The commands and the rules are in README.md.

- Revision: %s
- Scope: test/language, test/built-ins, test/annexB, test/harness
- Wall time: %v on %d workers
- All tests: %d, pass %d, fail %d, skip %d
- language + built-ins: %d run, %d pass (%s)
- annexB: %d run, %d pass (%s)

`, rev, rep.Wall.Round(100*time.Millisecond), rep.Workers, all.total(), all.pass, all.fail, all.skip,
		scope.pass+scope.fail, scope.pass, scope.rate(), annexB.pass+annexB.fail, annexB.pass, annexB.rate())

	b.WriteString("## By directory\n\n| Directory | Tests | Pass | Fail | Skip | Pass rate (run) |\n|---|--:|--:|--:|--:|--:|\n")
	names := make([]string, 0, len(groups))
	for g := range groups {
		names = append(names, g)
	}
	sort.Strings(names)
	for _, g := range names {
		c := groups[g]
		fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %s |\n", g, c.total(), c.pass, c.fail, c.skip, c.rate())
	}

	b.WriteString("\n## Skip reasons\n\n| Reason | Tests |\n|---|--:|\n")
	for _, kv := range sortedByCount(skips) {
		fmt.Fprintf(&b, "| %s | %d |\n", kv.key, kv.n)
	}

	b.WriteString("\n## Implemented features\n\nThe table in features.go; tests listing the feature or including a harness file that\nimplies it.\n\n| Feature | Tests | Pass | Fail | Skip | Pass rate (run) |\n|---|--:|--:|--:|--:|--:|\n")
	var fnames []string
	for f := range features {
		fnames = append(fnames, f)
	}
	sort.Strings(fnames)
	for _, f := range fnames {
		if c := features[f]; implemented[f] {
			fmt.Fprintf(&b, "| %s | %d | %d | %d | %d | %s |\n", f, c.total(), c.pass, c.fail, c.skip, c.rate())
		}
	}
	b.WriteString("\n## Features not implemented\n\nEvery test listing one of these is skipped. \"Only blocker\" counts the skipped tests\nthat this feature alone keeps from running.\n\n| Feature | Tests | Only blocker |\n|---|--:|--:|\n")
	slices.SortStableFunc(fnames, func(x, y string) int { return cmp.Compare(features[y].total(), features[x].total()) })
	for _, f := range fnames {
		if c := features[f]; !implemented[f] {
			note := ""
			if nonGoal(f) {
				note = " (non-goal)"
			}
			fmt.Fprintf(&b, "| %s%s | %d | %d |\n", f, note, c.total(), c.only)
		}
	}

	b.WriteString("\n## Top failure categories\n\nFailures grouped by message (the first line of the error, values elided).\n\n| Tests | Category | Example |\n|--:|---|---|\n")
	type cat struct {
		msg   string
		paths []string
	}
	var cats []cat
	for m, ps := range categories {
		cats = append(cats, cat{m, ps})
	}
	slices.SortFunc(cats, func(x, y cat) int {
		return cmp.Or(cmp.Compare(len(y.paths), len(x.paths)), cmp.Compare(x.msg, y.msg))
	})
	for _, c := range cats[:min(len(cats), 60)] {
		fmt.Fprintf(&b, "| %d | %s | %s |\n", len(c.paths), mdEscape(c.msg), c.paths[0])
	}

	fmt.Fprintf(&b, "\n## Panics\n\n%d tests panic in Go (each is an engine bug).\n", len(panics))
	if len(panics) > 0 {
		b.WriteString("\n| Test | Panic |\n|---|---|\n")
		for _, p := range panics[:min(len(panics), 40)] {
			fmt.Fprintf(&b, "| %s | %s |\n", p.Path, mdEscape(p.Message))
		}
	}
	fmt.Fprintf(&b, "\n## Timeouts\n\n%d tests hit the %v interrupt.\n", len(timeouts), Timeout)
	for _, p := range timeouts[:min(len(timeouts), 40)] {
		fmt.Fprintf(&b, "- %s\n", p.Path)
	}
	return b.String()
}

type keyCount struct {
	key string
	n   int
}

func sortedByCount(m map[string]int) []keyCount {
	var out []keyCount
	for k, n := range m {
		out = append(out, keyCount{k, n})
	}
	slices.SortFunc(out, func(x, y keyCount) int { return cmp.Or(cmp.Compare(y.n, x.n), cmp.Compare(x.key, y.key)) })
	return out
}

// mdEscape makes a message safe inside a table cell.
func mdEscape(s string) string {
	return strings.NewReplacer("|", `\|`, "\n", " ", "`", "'").Replace(s)
}
